name: flutter_projects
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Mantido o seu SDK para >=3.0.0 <4.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Para internacionalização (R5)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # ATUALIZADO para a versão exigida por flutter_localizations
  provider: ^6.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  # sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Versão estável. Pode ser ajustada se quiser usar a mais recente, mas esta deve funcionar.
  flutter_launcher_icons: ^0.13.1 # Versão estável. Pode ser ajustada se quiser usar a mais recente.
  # Para geração de código de internacionalização e assets (R5)
  flutter_gen: ^5.3.0 # Versão atualizada e estável
  flutter_gen_runner: ^5.10.0 # <--- CORRIGIDO AQUI! Esta é a versão que o Flutter está pedindo.

flutter:
  uses-material-design: true
  generate: true # ESSA LINHA É CRUCIAL PARA A GERAÇÃO DE LOCALIZAÇÕES

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations

  # Caso você tenha assets (imagens, etc.) em seu projeto, descomente e ajuste:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Caso você tenha fontes personalizadas em seu projeto, descomente e ajuste:
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf
  #       - asset: assets/fonts/MyCustomFont-Bold.ttf
  #         weight: 700