name: pc_10_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8

  # Floor: ORM para SQLite
  floor: ^1.4.2
  sqflite: ^2.3.3+1
  path: ^1.8.3
  path_provider: ^2.1.2

  # Gerenciador de estado
  provider: ^6.1.2

  # Internacionalização
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Geração do código Floor
  floor_generator: ^1.4.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Necessário para gerar arquivos de tradução
  generate: true
